services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SOURCE_URL: https://stream.radio-t.com/
      FILE_PREFIX: radio-t_
      SCHEDULE: 00 20 * * sat
      OUTPUT_DIRECTORY: /tmp/output
      DURATION: 4h
      LOG_LEVEL: debug
    volumes:
      - ./records:/tmp/output
